error: Fix template render
Since application data cannot be read by the error handler, it would
fail to render the error page correctly. This fixes that, by using
the revision macro twice.