error: Implement rendered error responses
As a footnote, while working in the following commit, I found that
Askama templates through askama_axum don't send their MIME type. This
might need to be worked on within the next commit.